#!/bin/bash

# Network Switch Script for KhipuVault
# Usage: ./scripts/switch-network.sh [testnet|mainnet]

set -e

NETWORK=${1:-testnet}
ENV_FILE="apps/web/.env.local"

if [ "$NETWORK" != "testnet" ] && [ "$NETWORK" != "mainnet" ]; then
  echo "❌ Error: Network must be 'testnet' or 'mainnet'"
  echo "Usage: ./scripts/switch-network.sh [testnet|mainnet]"
  exit 1
fi

echo "🔄 Switching to $NETWORK..."

# Backup current .env.local
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.backup"
  echo "✅ Backed up current config to $ENV_FILE.backup"
fi

# Create new .env.local based on network
cat > "$ENV_FILE" << EOF
# KhipuVault - ${NETWORK^^} Configuration
# Generated by switch-network.sh on $(date)

# Next.js
NEXT_PUBLIC_APP_URL=http://localhost:9002

# API Backend
NEXT_PUBLIC_API_URL=http://localhost:3001/api

# Privy - Web3 Authentication
NEXT_PUBLIC_PRIVY_APP_ID=

# Network Configuration
NEXT_PUBLIC_NETWORK=$NETWORK
EOF

if [ "$NETWORK" = "testnet" ]; then
  cat >> "$ENV_FILE" << EOF

# Testnet Chain Info (Auto-configured)
NEXT_PUBLIC_CHAIN_ID=31611
NEXT_PUBLIC_RPC_URL=https://rpc.test.mezo.org
EOF
  echo ""
  echo "✅ Switched to TESTNET"
  echo "📍 Chain ID: 31611"
  echo "🔗 RPC: https://rpc.test.mezo.org"
  echo "🌐 App will show: Full app with testnet banner"
else
  cat >> "$ENV_FILE" << EOF

# Mainnet Chain Info (Auto-configured)
NEXT_PUBLIC_CHAIN_ID=60808
NEXT_PUBLIC_RPC_URL=https://rpc.mezo.org
EOF
  echo ""
  echo "✅ Switched to MAINNET"
  echo "📍 Chain ID: 60808"
  echo "🔗 RPC: https://rpc.mezo.org"
  echo "🌐 App will show: Coming Soon page"
fi

echo ""
echo "⚠️  Important: Restart your dev server for changes to take effect"
echo ""
echo "Commands:"
echo "  pnpm dev         # Start development server"
echo "  pnpm build       # Test production build"
echo ""
echo "To revert: cp $ENV_FILE.backup $ENV_FILE"
